import type {
  ChecklistRun,
  Client,
  Equipment,
  GeneratedReportVersion,
  Measurement,
  MeasurementPoint,
  PhotoRecord,
  Project,
  SeedBundle,
  SignatureRecord,
  SyncQueueItem,
  UserProfile,
} from "./types";

const now = "2026-04-12T09:30:00-04:00";

export const sampleUser: UserProfile = {
  id: "usr-tech-01",
  fullName: "Camila Rojas",
  email: "camila.rojas@northacoustics.cl",
  role: "technician",
  phone: "+56 9 8765 4321",
};

export const sampleClients: Client[] = [
  {
    id: "cli-001",
    name: "Forestal Santa Aurora SpA",
    companyRut: "76.512.430-1",
    address: "Camino Industrial 1450, Coronel",
    contactName: "Patricio Mella",
    contactEmail: "pmella@santaaurora.cl",
    phone: "+56 41 245 8811",
    notes: "Cliente recurrente para campañas de ruido industrial.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cli-002",
    name: "Inmobiliaria Bahía Azul Ltda.",
    companyRut: "77.103.220-9",
    address: "Av. Costanera 812, Puerto Montt",
    contactName: "Francisca Soto",
    contactEmail: "francisca.soto@bahiaazul.cl",
    phone: "+56 65 232 1110",
    notes: "Proyecto con evaluación de receptores sensibles.",
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleProjects: Project[] = [
  {
    id: "pro-001",
    clientId: "cli-001",
    name: "Campaña Ruido Planta Astillas Norte",
    internalCode: "NAF-2026-041",
    siteAddress: "Ruta 160 km 18, Lote 4, Coronel",
    district: "Coronel",
    region: "Biobío",
    visitDate: "2026-04-11",
    professionalResponsible: "Ing. Paula Alvarado",
    studyObjective: "Caracterizar el ruido operacional diurno y nocturno de la planta.",
    reportType: "Informe de ruido DS 38",
    applicableRegulation: "DS N°38/2011 MMA",
    generalNotes: "Se solicitó especial atención en receptores del borde oriente.",
    status: "reviewed",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pro-002",
    clientId: "cli-002",
    name: "Línea Base Acústica Condominio Mirador",
    internalCode: "NAF-2026-052",
    siteAddress: "Pasaje Los Navegantes 121, Puerto Montt",
    district: "Puerto Montt",
    region: "Los Lagos",
    visitDate: "2026-04-10",
    professionalResponsible: "Ing. Diego Quezada",
    studyObjective: "Levantamiento de línea base acústica para Declaración Ambiental.",
    reportType: "Informe línea base",
    applicableRegulation: "Guía SEA + DS N°38/2011 MMA",
    generalNotes: "Zona expuesta a tránsito y actividad portuaria.",
    status: "measured",
    createdAt: now,
    updatedAt: now,
  },
];

export const samplePoints: MeasurementPoint[] = [
  {
    id: "pt-001",
    projectId: "pro-001",
    code: "P1-Borde Oriente",
    latitude: -37.0059,
    longitude: -73.1424,
    photoUri: "https://images.unsplash.com/photo-1513828646384-e4d8ec30d2bb",
    environmentDescription: "Vivienda aislada con cierre perimetral y vegetación baja.",
    sketchReference: "Acceso por calle lateral, frente a portón verde.",
    landUse: "Residencial",
    nearestSensitiveReceiver: "Vivienda unifamiliar",
    estimatedDistanceToSourceM: 145,
    notes: "Presencia de ruido intermitente por tránsito liviano.",
    measuredAt: "2026-04-11T21:10:00-04:00",
    recordedBy: "Camila Rojas",
    status: "reviewed",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pt-002",
    projectId: "pro-001",
    code: "P2-Acceso Planta",
    latitude: -37.0035,
    longitude: -73.1392,
    photoUri: "https://images.unsplash.com/photo-1504307651254-35680f356dfd",
    environmentDescription: "Frente a ingreso de camiones y barrera acústica parcial.",
    sketchReference: "A 5 m del poste de iluminación principal.",
    landUse: "Industrial",
    nearestSensitiveReceiver: "Caseta de vigilancia",
    estimatedDistanceToSourceM: 25,
    notes: "Fuente dominante por maniobra de carga.",
    measuredAt: "2026-04-11T22:00:00-04:00",
    recordedBy: "Camila Rojas",
    status: "measured",
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleMeasurements: Measurement[] = [
  {
    id: "me-001",
    pointId: "pt-001",
    measurementType: "Ruido ambiente nocturno",
    startedAt: "2026-04-11T21:15:00-04:00",
    endedAt: "2026-04-11T22:15:00-04:00",
    durationMinutes: 60,
    laeq: 51.8,
    lmax: 63.1,
    lmin: 42.2,
    l10: 56.4,
    l50: 50.9,
    l90: 45.1,
    weighting: "A",
    equipmentResponse: "Fast",
    equipmentName: "Svantek SVAN 977",
    soundLevelMeterCode: "SLM-NA-04",
    serialNumber: "SV977-180245",
    calibratorName: "Larson Davis CAL200",
    initialCalibration: 94,
    finalCalibration: 93.9,
    validity: "valid",
    technicalNotes: "Sin eventos extraordinarios durante la integración.",
    environmentalConditions: {
      temperatureC: 14.3,
      relativeHumidity: 71,
      windSpeedMs: 1.8,
      cloudiness: "Parcial",
      weatherState: "Despejado",
      weatherNotes: "Viento bajo y constante desde el sur.",
      externalEvidence: "Anemómetro portátil Kestrel 3000",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "me-002",
    pointId: "pt-002",
    measurementType: "Control de fuente emisora",
    startedAt: "2026-04-11T22:20:00-04:00",
    endedAt: "2026-04-11T22:50:00-04:00",
    durationMinutes: 30,
    laeq: 68.2,
    lmax: 76.4,
    lmin: 58.1,
    l10: 71.3,
    l50: 66.9,
    l90: 61.4,
    weighting: "A",
    equipmentResponse: "Fast",
    equipmentName: "Svantek SVAN 977",
    soundLevelMeterCode: "SLM-NA-04",
    serialNumber: "SV977-180245",
    calibratorName: "Larson Davis CAL200",
    initialCalibration: 94,
    finalCalibration: 94.1,
    validity: "valid",
    technicalNotes: "Se identificó maniobra puntual de retroceso a las 22:41.",
    environmentalConditions: {
      temperatureC: 13.9,
      relativeHumidity: 72,
      windSpeedMs: 2.3,
      cloudiness: "Cubierto",
      weatherState: "Nublado",
      weatherNotes: "Sin precipitaciones.",
      externalEvidence: "Observación directa del técnico",
    },
    createdAt: now,
    updatedAt: now,
  },
];

export const samplePhotos: PhotoRecord[] = [
  {
    id: "ph-001",
    projectId: "pro-001",
    pointId: "pt-001",
    category: "measurement_point",
    uri: "https://images.unsplash.com/photo-1513828646384-e4d8ec30d2bb",
    capturedAt: "2026-04-11T21:08:00-04:00",
    capturedBy: "Camila Rojas",
    latitude: -37.0059,
    longitude: -73.1424,
  },
  {
    id: "ph-002",
    projectId: "pro-001",
    measurementId: "me-002",
    pointId: "pt-002",
    category: "installed_equipment",
    uri: "https://images.unsplash.com/photo-1504307651254-35680f356dfd",
    capturedAt: "2026-04-11T22:18:00-04:00",
    capturedBy: "Camila Rojas",
    latitude: -37.0035,
    longitude: -73.1392,
  },
];

export const sampleEquipment: Equipment[] = [
  {
    id: "eq-001",
    type: "sound_level_meter",
    brand: "Svantek",
    model: "SVAN 977",
    serialNumber: "SV977-180245",
    calibrationCertificateUrl: "https://example.com/certificados/svan977.pdf",
    calibrationDueDate: "2026-12-18",
    attachmentUrl: "https://example.com/certificados/svan977.pdf",
  },
  {
    id: "eq-002",
    type: "calibrator",
    brand: "Larson Davis",
    model: "CAL200",
    serialNumber: "CAL200-88102",
    calibrationCertificateUrl: "https://example.com/certificados/cal200.pdf",
    calibrationDueDate: "2026-10-05",
    attachmentUrl: "https://example.com/certificados/cal200.pdf",
  },
];

export const sampleChecklistRuns: ChecklistRun[] = [
  {
    id: "ck-001",
    projectId: "pro-001",
    pointId: "pt-001",
    technicianId: "usr-tech-01",
    items: [
      { id: "1", label: "Equipo calibrado", completed: true },
      { id: "2", label: "Batería suficiente", completed: true },
      { id: "3", label: "Punto correctamente identificado", completed: true },
      { id: "4", label: "Condiciones ambientales aceptables", completed: true },
      { id: "5", label: "Fotografías tomadas", completed: true },
      { id: "6", label: "Coordenadas capturadas", completed: true },
      { id: "7", label: "Observaciones registradas", completed: true },
    ],
    technicianConfirmation: "Camila Rojas",
    createdAt: "2026-04-11T21:05:00-04:00",
  },
];

export const sampleSignatures: SignatureRecord[] = [
  {
    id: "sg-001",
    entityType: "project",
    entityId: "pro-001",
    signedBy: "Camila Rojas",
    role: "technician",
    signedAt: "2026-04-11T23:05:00-04:00",
    signatureLabel: "Firma simple terreno",
  },
  {
    id: "sg-002",
    entityType: "report",
    entityId: "rep-001",
    signedBy: "Paula Alvarado",
    role: "supervisor",
    signedAt: "2026-04-12T09:00:00-04:00",
    signatureLabel: "Validación supervisor",
  },
];

export const sampleReports: GeneratedReportVersion[] = [
  {
    id: "rep-001",
    projectId: "pro-001",
    version: 2,
    status: "generated",
    storagePath: "generated-reports/pro-001/v2/informe-ruido.html",
    generatedAt: "2026-04-12T08:40:00-04:00",
    generatedBy: "Paula Alvarado",
  },
];

export const sampleSyncQueue: SyncQueueItem[] = [
];

export const seedBundle: SeedBundle = {
  currentUser: sampleUser,
  clients: sampleClients,
  projects: sampleProjects,
  points: samplePoints,
  measurements: sampleMeasurements,
  photos: samplePhotos,
  equipment: sampleEquipment,
  checklistRuns: sampleChecklistRuns,
  signatures: sampleSignatures,
  reports: sampleReports,
  syncQueue: sampleSyncQueue,
};
